
FROM ghcr.io/astral-sh/uv:alpine

RUN apk add build-base curl

WORKDIR /app

COPY pyproject.toml .
COPY uv.lock .


RUN uv sync --locked

COPY ./templates ./templates
COPY ./app.py .

HEALTHCHECK --start-period=10s --start-interval=0.5s --interval=0.5s CMD curl -f 127.0.0.1:8080/health || exit 1

CMD ["uv", "run", "app.py"]
